server:
  port: 8040
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/serenityprayer/micro-services
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: config-server/config-repo
          # git仓库的账号和密码
          username:
          password:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8000/eureka/
  instance:
    prefer-ip-address: true